from typing import List, Dict

loc_sets: Dict[str, List[str]] = {
    "Quests": [
        "MarshSpawn.TokkKeystoneQuest",
        "MarshSpawn.MokkFangQuest",
        "MarshSpawn.TokkTabletQuest",
        "EastHollow.KwolokAmuletQuest",
        "OuterWellspring.TheLostCompass",
        "WoodsEntry.TreeSeed",
        "EastPools.KwolokAmuletQI",
        "LowerWastes.EerieGemQI",
        "GladesTown.TwillenGemQuest",
        "GladesTown.FamilyReunionKey",
        "GladesTown.MokiAcornQuest",
    ],
    "HandToHand": [
        "EastHollow.HandToHandMap",
        "GladesTown.HandToHandPouch",
        "InnerWellspring.HandToHandHerbs",
        "LowerReach.HandToHandSoup",
        "LowerReach.HandToHandHat",
        "GladesTown.HandToHandLantern",
        "LowerDepths.HandToHandSilk",
        "EastPools.HandToHandSpyglass",
        "GladesTown.HandToHandCanteen",
        "LowerWastes.HandToHandMapstone",
        "WindtornRuins.HandToHandComplete",
    ],
    "ExtraQuests": [
        "MarshSpawn.CaveKS",
        "MarshSpawn.FangQI",
        "HowlsDen.SwordTree",
        "MidnightBurrows.TabletQI",
        "EastHollow.ForestsVoice",
        "GladesTown.AcornQI",
        "InnerWellspring.NeedleQI",
        "InnerWellspring.BlueMoonSeed",
        "InnerWellspring.WaterEscape",
        "WoodsEntry.DollQI",
        "LowerReach.ForestsMemory",
        "UpperReach.SpringSeed",
        "UpperDepths.LightcatcherSeed",
        "UpperDepths.ForestsEyes",
        "EastPools.GrassSeed",
        "WestPools.ForestsStrength",
        "UpperWastes.FlowersSeed",
        "WindtornRuins.Seir",
    ],
    "Rebuild": [
        "GladesTown.RebuildTheGlades",
        "GladesTown.RegrowTheGlades",
    ],
    "Trials": [
        "MarshPastOpher.SpiritTrial",
        "WestHollow.SpiritTrial",
        "OuterWellspring.SpiritTrial",
        "EastPools.SpiritTrial",
        "WoodsMain.SpiritTrial",
        "LowerReach.SpiritTrial",
        "LowerDepths.SpiritTrial",
        "LowerWastes.SpiritTrial",
    ],
    "QOL": [
        "WoodsEntry.LastTreeBranch"
    ],
    }
